services:

  mongo_GomokuGame:
    networks:
      - mynetwork_GomokuGame
    image: mongo:4.4.18
    container_name: mongo_GomokuGame
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mijn_geheime_mongodb_wachtwoord
    ports:
      - "27019:27017"
    volumes:
      - ./mongodata:/data/db

  GomokuGame:
    container_name: GomokuGame
    networks:
      - mynetwork_GomokuGame
    build: ./GomokuGame
    ports:
      - "5002:5000"
    volumes:
      - ./GomokuGame:/app  # Dankzij deze regel, en de volgende regel in je flask-app
                # kun je je python code on the fly aanpassen, en wordt het
                # na wijziging automatisch gereload.
                # Je hoeft dan dus alleen nog het image te rebuilden als 
                # requirements.txt verandert.
                # Binnen de docker container wordt dan een app volume gemaakt
                # waar alles in wordt gezet.
                # Maar soms is restarten nodig:
                # docker-compose restart gomoku
    environment:
      - APP_SECRET_KEY=mijn_geheime_GomokuGame_applicatie_sleutel
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mijn_geheime_mongodb_wachtwoord
      - MONGO_HOST=mongo_GomokuGame  # Docker-service naam van MongoDB (gebruikt in de Flask-app voor verbinding)
      - FLASK_ENV=development # debug modus: daardoor rebuild de container automatisch na een wijziging.
                             # NB: gebruik in dit geval in de Dockerfile: CMD ["python", "app.py"]
      #- FLASK_ENV=production # production modus: dat geeft beter gedrag bij meer bezoekers.
                             # NB: gebruik in dit geval in de Dockerfile: CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "app:app"]
    restart: unless-stopped
                
networks:
  mynetwork_GomokuGame:
